### ISSUE TITLE
Can we change it to parse English reumes

### ISSUE THREAD

**Issue by yashdeo55** [chen0040/keras-chinese-resume-parser-and-analyzer#1]

**Comment by chen0040** [comment]
hi @yashdeo55 majority of the current parser can be used for english resume, the parsing rules might be a bit different for the english resumes, which you can modify in the keras_cn_parser_and_analyzer/library/utility/parser_rules.py

**Comment by chen0040** [comment]
hi @yashdeo55 I have created a separate project https://github.com/chen0040/keras-english-resume-parser-and-analyzer which allows one to parser english resume instead. The changes include replacing SnowNLP to word_tokenization in chinese with NLTK for english. as well as modifying the rule-based parsing in the keras_en_parser_and_analyzer/library/utility/parser_rules.py. The ResumeParser for rule-based-parser.py in the english version may not be working very well as i only wrote the rules for a very small data set i collected on english resumes. therefore, if you are using the rule-based-parser.py you may want to modify the parsing rules in keras_en_parser_and_analyzer/library/utility/parser_rules.py. However, you can also use the deep learning based approach as suggested in the ReadMe.md. The best can be achieved by using the ResumeParser in the dl-based-parser.py and updating the rules in keras_cn_parser_and_analyzer/library/utility/parser_rules.py
